apiVersion: v1
kind: Service
metadata: 
    name: product-app
    namespace: public-akashbhardwaj
    labels:
        app: product-app
spec:
    type: LoadBalancer
    selector:
        app: product-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80